name: Tests

on: [ push, pull_request ]

jobs:
  unit-benchmark-test:
    strategy:
      matrix:
        go: [ 1.17, 1.18, 1.19, 1.20, 1.21 ]
        os: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

       # block scenario, comment temporarily
#      - uses: actions/cache@v3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Run Tests
        run: ./run.sh
